//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dumper
{
    [Serializable]
    public class DetectedRadarObjectMsg : Message
    {
        public const string k_RosMessageName = "dumper_msgs/DetectedRadarObject";
        public override string RosMessageName => k_RosMessageName;

        public int id;
        public Geometry.Vector3Msg sensor_aim;
        public Geometry.Vector3Msg sensor_right;
        public Geometry.PointMsg sensor_position;
        public Geometry.Vector3Msg sensor_velocity;
        public double sensor_angle;
        public Geometry.PointMsg object_position;
        public Geometry.Vector3Msg object_velocity;
        public Geometry.PointMsg object_relative_position;
        public Geometry.Vector3Msg object_relative_velocity;
        public Geometry.Vector3Msg object_collider_size;
        public byte object_state;
        public bool new_detection;
        public const byte STATE_MOVING = 0;
        public const byte STATE_STATIONARY = 1;

        public DetectedRadarObjectMsg()
        {
            this.id = 0;
            this.sensor_aim = new Geometry.Vector3Msg();
            this.sensor_right = new Geometry.Vector3Msg();
            this.sensor_position = new Geometry.PointMsg();
            this.sensor_velocity = new Geometry.Vector3Msg();
            this.sensor_angle = 0.0;
            this.object_position = new Geometry.PointMsg();
            this.object_velocity = new Geometry.Vector3Msg();
            this.object_relative_position = new Geometry.PointMsg();
            this.object_relative_velocity = new Geometry.Vector3Msg();
            this.object_collider_size = new Geometry.Vector3Msg();
            this.object_state = 0;
            this.new_detection = false;
        }

        public DetectedRadarObjectMsg(int id, Geometry.Vector3Msg sensor_aim, Geometry.Vector3Msg sensor_right, Geometry.PointMsg sensor_position, Geometry.Vector3Msg sensor_velocity, double sensor_angle, Geometry.PointMsg object_position, Geometry.Vector3Msg object_velocity, Geometry.PointMsg object_relative_position, Geometry.Vector3Msg object_relative_velocity, Geometry.Vector3Msg object_collider_size, byte object_state, bool new_detection)
        {
            this.id = id;
            this.sensor_aim = sensor_aim;
            this.sensor_right = sensor_right;
            this.sensor_position = sensor_position;
            this.sensor_velocity = sensor_velocity;
            this.sensor_angle = sensor_angle;
            this.object_position = object_position;
            this.object_velocity = object_velocity;
            this.object_relative_position = object_relative_position;
            this.object_relative_velocity = object_relative_velocity;
            this.object_collider_size = object_collider_size;
            this.object_state = object_state;
            this.new_detection = new_detection;
        }

        public static DetectedRadarObjectMsg Deserialize(MessageDeserializer deserializer) => new DetectedRadarObjectMsg(deserializer);

        private DetectedRadarObjectMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            this.sensor_aim = Geometry.Vector3Msg.Deserialize(deserializer);
            this.sensor_right = Geometry.Vector3Msg.Deserialize(deserializer);
            this.sensor_position = Geometry.PointMsg.Deserialize(deserializer);
            this.sensor_velocity = Geometry.Vector3Msg.Deserialize(deserializer);
            deserializer.Read(out this.sensor_angle);
            this.object_position = Geometry.PointMsg.Deserialize(deserializer);
            this.object_velocity = Geometry.Vector3Msg.Deserialize(deserializer);
            this.object_relative_position = Geometry.PointMsg.Deserialize(deserializer);
            this.object_relative_velocity = Geometry.Vector3Msg.Deserialize(deserializer);
            this.object_collider_size = Geometry.Vector3Msg.Deserialize(deserializer);
            deserializer.Read(out this.object_state);
            deserializer.Read(out this.new_detection);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.sensor_aim);
            serializer.Write(this.sensor_right);
            serializer.Write(this.sensor_position);
            serializer.Write(this.sensor_velocity);
            serializer.Write(this.sensor_angle);
            serializer.Write(this.object_position);
            serializer.Write(this.object_velocity);
            serializer.Write(this.object_relative_position);
            serializer.Write(this.object_relative_velocity);
            serializer.Write(this.object_collider_size);
            serializer.Write(this.object_state);
            serializer.Write(this.new_detection);
        }

        public override string ToString()
        {
            return "DetectedRadarObjectMsg: " +
            "\nid: " + id.ToString() +
            "\nsensor_aim: " + sensor_aim.ToString() +
            "\nsensor_right: " + sensor_right.ToString() +
            "\nsensor_position: " + sensor_position.ToString() +
            "\nsensor_velocity: " + sensor_velocity.ToString() +
            "\nsensor_angle: " + sensor_angle.ToString() +
            "\nobject_position: " + object_position.ToString() +
            "\nobject_velocity: " + object_velocity.ToString() +
            "\nobject_relative_position: " + object_relative_position.ToString() +
            "\nobject_relative_velocity: " + object_relative_velocity.ToString() +
            "\nobject_collider_size: " + object_collider_size.ToString() +
            "\nobject_state: " + object_state.ToString() +
            "\nnew_detection: " + new_detection.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
