//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dumper
{
    [Serializable]
    public class DetectedRadarObjectArrayMsg : Message
    {
        public const string k_RosMessageName = "dumper_msgs/DetectedRadarObjectArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public DetectedRadarObjectMsg[] objects;

        public DetectedRadarObjectArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.objects = new DetectedRadarObjectMsg[0];
        }

        public DetectedRadarObjectArrayMsg(Std.HeaderMsg header, DetectedRadarObjectMsg[] objects)
        {
            this.header = header;
            this.objects = objects;
        }

        public static DetectedRadarObjectArrayMsg Deserialize(MessageDeserializer deserializer) => new DetectedRadarObjectArrayMsg(deserializer);

        private DetectedRadarObjectArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.objects, DetectedRadarObjectMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.objects);
            serializer.Write(this.objects);
        }

        public override string ToString()
        {
            return "DetectedRadarObjectArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\nobjects: " + System.String.Join(", ", objects.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
